apiVersion: v2
kind: Service
metadata:
  name: mlg
  labels:
    app: mlg
    group: web
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 32088
    protocol: TCP
  selector:
    app: mlg
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mlg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlg
  template:
    metadata:
      labels:
        app: mlg
        group: web
        tier: frontend
    spec:
      containers:
      - name: mlg
        image: misegr/jupyter-mlg
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: mlg
        # Volumes im Container
        volumeMounts:
        - mountPath: "/data"
          subPath: mlg
          name: "mlg-data"
      # Volumes in Host
      volumes:
      - name: "mlg-data"
        persistentVolumeClaim:
         claimName: data-claim
